# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnapKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapKitDemo
 	pod 'SnapKit', '~> 4.0.0'
end
